class ErrorCode:
    XML_FORMAT_ERROR = 31
    XML_STRUCTURE_ERROR = 32

    SEMANTIC_ERROR = 52
    RUNTIME_WRONG_TYPE = 53
    RUNTIME_UNDEF_VAR = 54
    RUNTIME_NONEXIST_FRAME = 55
    RUNTIME_MISSING_VALUE = 56
    RUNTIME_WRONG_VALUE = 57
    RUNTIME_STRING_HANDLING = 58

    UNDEFINED_ERROR = 99
